# Generated by Django 4.0.4 on 2022-05-02 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerNumber', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=100)),
                ('Street', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=30)),
                ('PhoneNumber', models.PositiveIntegerField()),
                ('Language', models.CharField(max_length=30)),
                ('Created', models.DateField(default=datetime.date.today)),
                ('Status', models.BooleanField()),
                ('Discount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('InventoryId', models.AutoField(primary_key=True, serialize=False)),
                ('InventoryLocationName', models.CharField(max_length=100)),
                ('ProductId', models.PositiveIntegerField()),
                ('ProductName', models.CharField(max_length=100)),
                ('CycleCounting', models.PositiveIntegerField()),
                ('ProductUOM', models.CharField(max_length=10)),
                ('AvalableQuantity', models.PositiveIntegerField()),
                ('ReceivedQuantity', models.PositiveIntegerField()),
                ('SoldQuantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductCategory', models.CharField(max_length=100)),
                ('ProductUOM', models.CharField(max_length=10)),
                ('CostPrice', models.FloatField()),
                ('SalesPrice', models.FloatField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('SalesOrderId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerNumber', models.PositiveIntegerField()),
                ('CustomerName', models.CharField(max_length=100)),
                ('ProductId', models.PositiveIntegerField()),
                ('ProductName', models.CharField(max_length=100)),
                ('ProductUOM', models.CharField(max_length=10)),
                ('SalesQuantity', models.PositiveIntegerField()),
                ('SalesPrice', models.FloatField()),
                ('Amount', models.FloatField()),
                ('SalesOrderDate', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
